TrainingSpot.create(name: "大垣総合体育館")
TrainingSpot.create(name: "大垣武道館")
TrainingSpot.create(name: "岐阜市もえぎの里多目的体育館")
TrainingSpot.create(name: "尾西スポーツセンター")
TrainingSpot.create(name: "一宮市総合体育館")
TrainingSpot.create(name: "138トレーニングジム")
TrainingSpot.create(name: "フィットイージー大垣東店")
TrainingSpot.create(name: "FIt365イオンモール大垣店")